apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mlflow-asdp-serve
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mlflow-asdp-serve
  template:
    metadata:
      labels:
        app: mlflow-asdp-serve
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mlflow-asdp-serve
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-mlflow-asdp-serve-env-configmap
            - secretRef:
                name: {{ .Release.Name }}-mlflow-asdp-serve-env-secret
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /version
              port: {{ .Values.service.name }}
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /version
              port: {{ .Values.service.name }}
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /version
              port: {{ .Values.service.name }}
            periodSeconds: 10
            failureThreshold: 30
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
