apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mlflow-asdp-serve-env-secret
  labels:
    app: mlflow-asdp-serve
type: Opaque
data:
{{- if .Values.mlflow.enabled }}
{{- if .Values.mlflow.tracking.token }}
  MLFLOW_TRACKING_TOKEN: {{ required "MLflow Tracking Server token must be specified" .Values.mlflow.tracking.token | b64enc }}
{{- end }}
{{- end }}
