apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mlflow-asdp-serve
  labels:
    app: mlflow-asdp-serve
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: mlflow-asdp-serve
